[mypy]
exclude = (html/|palindromi_fi_builder/static/)

disallow_any_unimported = True
disallow_any_expr = True
disallow_any_decorated = True
disallow_any_explicit = True

disallow_any_generics = True
disallow_subclassing_any = True

disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True

no_implicit_optional = True
strict_optional = True

warn_redundant_casts = True
warn_unused_ignores = True
warn_no_return = True
warn_return_any = True
warn_unreachable = True

ignore_errors = False

disallow_untyped_globals = True
no_implicit_reexport = True
strict_equality = True

show_error_context = True
show_error_codes = True

warn_unused_configs = True
strict_concatenate = True

[mypy-palindromi_fi_builder.load]
allow_any_expr = True

[mypy-palindromi_fi_builder.render]
allow_any_expr = True

[mypy-pkg_resources]
ignore_missing_imports = True

[mypy-ruamel]
ignore_missing_imports = True

