name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - name: Install dependencies
        run: pip install base58 click jinja2 ruamel.yaml transcrypt
      - name: Render the site into the "rendered" branch
        run: |
          export REMOTE_REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          make render_to_branch
      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.2.9
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('.github/actions/upload-rendered/*') }}
      - name: Upload the rendered site to Google Cloud Storage when merging to main
        uses: ./.github/actions/upload-rendered
        with:
          secrets: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
