name: Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
 darker:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
     - uses: actions/setup-python@v4
     - uses: akaihola/darker@1.7.0
       with:
         version: "@master"
         options: "--check --diff --isort --color"
         src: "./palindromi_fi_builder"
         revision: "origin/main..."
