name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  graylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v10.2.0
        with:
          version: "0.12.17"
          python-version: "3.11"
      - name: Install dependencies
        run: uv sync --frozen
      - name: Lint changed code
        run: >-
          uv run --no-sync graylint --color --revision origin/main...
          -L flake8 -L mypy -L pylint ./palindromi_fi_builder
